language: generic
sudo: required

services: docker

before_install:
  - docker build -t votechain/front -f Dockerfile.dev .

script:
  - docker run -e CI=true votechain/front yarn test

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker build -t votechain-front .
  - docker tag votechain-front $DOCKER_ID/votechain-front
  - docker push $DOCKER_ID/votechain-front
