sudo: required

services: docker

cache:
  directories:
    - node_modules

before_install:
  - docker build -t votechain/front -f Dockerfile.dev .

script:
  - docker run -e CI=true votechain/front yarn test
