steps:
  # build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/front-votechain/front-votechain-00001-zux', '.' ]
  # push the container image to gcr
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/front-votechain/front-votechain-00001-zux']
    # Deploy container image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args: ['run', 'deploy', 'front-votechain-00001-zux', '--image', 'gcr.io/front-votechain/front-votechain-00001-zux', '--region', 'europe-west4', '--platform', 'managed', '--allow-unauthenticated']
